### ISSUE TITLE
Add scheduled events through chat

### ISSUE THREAD

**Issue by WaltWh** [WaltWh/LongSphinx#29] opened 2019-01-02 05:46 UTC
Arguably a subtask of #5

**Comment by diziara** [comment] 2021-12-31 00:57
duplicate of #97 
Updated goal to reading events from external calendar instead of managing events within Discord.

**Comment by diziara** [comment] 2021-12-31 00:58
Updated goal to reading events from external calendar instead of managing events within Discord.

**Closed by diziara** 2021-12-31 00:58 UTC
Labels: enhancement, new module
